before:
  hooks:
    - go mod tidy -compat=1.17
builds:
  - main: ./cmd/mascaras/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
